/**
 * /preview/[id] にディスパッチ可能な animation id 一覧。
 * registry.tsx と scripts/build-thumbs.ts 両方から参照される
 * （後者は CSS Module を含む registry.tsx を直接 import できないため分離）。
 */
export const PREVIEW_IDS = [
  "entrance-stagger-fade",
  "hover-lift",
  "scroll-reveal",
  "fade-in",
  "spinner-dots",
  "skeleton-shimmer",
  "pulse-attention",
  "accordion-collapse",
  "fade-up",
  "scale-in",
  "blur-in",
  "hover-glow",
  "gsap-scroll-pin",
  "svg-line-draw",
  "css-scroll-driven",
  "slide-in-right",
  "hover-tilt",
  "hover-underline",
  "image-zoom",
  "modal-fade",
  "drawer-slide",
  "tab-switch",
  "toast-slide",
  "progress-bar",
  "shake",
  "bounce-in",
  "highlight-flash",
  "view-transition-fade",
  "view-transition-shared",
  "lottie-playback",
  "rive-state-machine",
  "drag-swipe-card",
  "drag-reorder",
  "count-up",
  "marquee",
  "cursor-spotlight",
  "sticky-shrink-header",
  "carousel-slider",
  "text-reveal-lines",
  "typewriter",
  "toggle-switch",
  "tooltip-pop",
  "dropdown-menu",
  "page-loading-bar",
  "magnetic-button",
  "modal-scale-blur",
  "dialog-focus-trap",
  "confirm-dialog-shake-on-no",
  "popover-anchor-positioning",
  "command-palette-cmdk",
] as const;

/** その id がパラメータ操作 UI に対応しているか（ParameterPanel 表示判定に使う） */
export const PARAM_AWARE_IDS = new Set<string>([
  "fade-up",
  "scale-in",
  "blur-in",
  "bounce-in",
  "hover-tilt",
  "fade-in",
  "slide-in-right",
  "marquee",
  "toast-slide",
  "count-up",
]);
